version: "3.6"

services: 
    postgres:
        build: "./postgres"
        restart: "always"
    environment: 
        POSTGRES_DB: "meower"
        POSTGRES_DB: "meower"
        POSTGRES_PASSWORD: "123456"
    
    nats:
        image: "nats-streaming:0.9.2"
        restart: "always"
    
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'